DULL=0
BRIGHT=1

FG_BLACK=30
FG_RED=31
FG_GREEN=32
FG_YELLOW=33
FG_BLUE=34
FG_VIOLET=35
FG_CYAN=36
FG_WHITE=37

FG_NULL=00

BG_BLACK=40
BG_RED=41
BG_GREEN=42
BG_YELLOW=43
BG_BLUE=44
BG_VIOLET=45
BG_CYAN=46
BG_WHITE=47

BG_NULL=00

##
# ANSI Escape Commands
##
# ESC="\033"
CSTART=""
CEND=""
ESC="\E"
NORMAL="$ESC[0m$CEND"
RESET="$CSTART$ESC[${DULL};${FG_WHITE};${BG_NULL}m$CEND"

BLACK="$CSTART$ESC[${DULL};${FG_BLACK}m$CEND"
RED="$CSTART$ESC[${DULL};${FG_RED}m$CEND"
GREEN="$CSTART$ESC[${DULL};${FG_GREEN}m$CEND"
YELLOW="$CSTART$ESC[${DULL};${FG_YELLOW}m$CEND"
BLUE="$CSTART$ESC[${DULL};${FG_BLUE}m$CEND"
VIOLET="$CSTART$ESC[${DULL};${FG_VIOLET}m$CEND"
CYAN="$CSTART$ESC[${DULL};${FG_CYAN}m$CEND"
WHITE="$CSTART$ESC[${DULL};${FG_WHITE}m$CEND"

# BRIGHT TEXT
BRIGHT_BLACK="$CSTART$ESC[${BRIGHT};${FG_BLACK}m$CEND"
BRIGHT_RED="$CSTART$ESC[${BRIGHT};${FG_RED}m$CEND"
BRIGHT_GREEN="$CSTART$ESC[${BRIGHT};${FG_GREEN}m$CEND"
BRIGHT_YELLOW="$CSTART$ESC[${BRIGHT};${FG_YELLOW}m$CEND"
BRIGHT_BLUE="$CSTART$ESC[${BRIGHT};${FG_BLUE}m$CEND"
BRIGHT_VIOLET="$CSTART$ESC[${BRIGHT};${FG_VIOLET}m$CEND"
BRIGHT_CYAN="$CSTART$ESC[${BRIGHT};${FG_CYAN}m$CEND"
BRIGHT_WHITE="$CSTART$ESC[${BRIGHT};${FG_WHITE}m$CEND"

