#!/bin/bash

workspace=$HOME/workspace
if [[ $# = 1 ]]; then
  if [ -d "$1" ]; then
    workspace=$1
  else
    echo "WARNING: $1 not a valid workspace path, falling back to default"
  fi
fi;

echo "using $workspace as root workspace"

if [[ -e /opt/git-forest/git-forest.sh ]]; then
  source /opt/git-forest/git-forest.sh
  # User Configuration file
  if [[ -e $workspace/config/user_conf.forest ]]; then
    configuration_set $workspace/config/user_conf.forest
  else
    echo "no user configuration, pull from the template and put at $workspace/config/user_conf.forest";
  fi
  # User seed file
  if [[ -e $workspace/seed/sergeant.forest ]]; then
    list_set $workspace/seed/sergeant.core.forest
  else
    echo "no default seed file, put your forest seeds in $workspace/seed/"
  fi
fi
