#!/bin/bash
[ $# == 0 ] && echo "need folder name" && exit
user=$(whoami);
source $HOME/.userrc
ipaddr=$1
netdir=$2
mountpoint=$3
mkdir -p ${mountpoint};

if mount|grep ${mountpoint}; then
    echo lazy umounting
    sudo umount ${mountpoint} -l
fi

echo mounting

sudo mount -t cifs -o username=$nuser,password=$(echo -n $userpass64 | base64 -d),uid=$user,gid=$user \
  //$ipaddr/c/cygwin64/home/$nuser/$netdir \
  ${mountpoint}

# sudo mount -t cifs -o username=$nuser,password=$(echo -n $userpass64 | base64 -d),rw,uid=vsftpd,gid=nogroup,file_mode=0770,dir_mode=0770 \
#   //$ipaddr/c/cygwin64/home/$nuser/$netdir \
#   ${mountpoint}

#
if test $? -eq 0;then
    echo mounted
else
    echo unable to mount
    exit
fi
{ while true; do echo caca > ${mountpoint}/keepalive; sleep 30; done }&
