#!/bin/sh 
[ $# == 0 ] && echo "need folder name" && exit
user=$(whoami);
source $HOME/.userrc
mountpoint=$HOME/$1
mkdir -p ${mountpoint};

if mount|grep ${mountpoint}; then
    echo lazy umounting
    sudo umount ${mountpoint} -l
fi

# sudo pgkill.py -fq mount_cifs.sh 
# rm ${mountpoint}/keepalive
echo mounting
# sudo mount -t cifs -o username=$2,password=$3,dir_mode=0777,file_mode=0777 $1 ${mountpoint}

sudo mount -t cifs -o username=$nuser,password=$(echo -n $userpass64 | base64 -d),uid=$user,gid=$user \
  //192.168.2.42/c/cygwin64/home/$nuser/$1 \
  ${mountpoint}
#
if test $? -eq 0;then
    echo mounted
else
    echo unable to mount
    exit
fi    
{ while true; do echo caca > ${mountpoint}/keepalive; sleep 30; done }&

