#!/usr/bin/python

import sys
import os
import json


def main():

  basepath = os.path.dirname(os.path.realpath(__file__))
  with open(os.path.join(basepath, 'acronym_master_list.json')) as f:
    acronym_dict = json.load(f)

  for line in sys.argv[1:]:
    acronym = line.strip()
    definition = acronym_dict[acronym] if acronym in acronym_dict.keys() else 'unknown'
    print("%s: %s" % (acronym, definition))

if __name__ == "__main__":
  main()
