#!/usr/bin/python
import os
extensions = set()
for root, dirs, files in os.walk("."):
  for file in files:
    extensions.add(os.path.splitext(os.path.join(root, file))[1])

for e in extensions:
  print(e)
