#!/usr/bin/env python
# -*- coding: utf-8 -*-


from __future__ import print_function
import os
import sys
import re
import argparse
import codecs
import fnmatch
import pypandoc


def main(arguments):

  parser = argparse.ArgumentParser(
      description=__doc__,
      formatter_class=argparse.RawDescriptionHelpFormatter)
  parser.add_argument('-i', '--infile', help="Input file")  # , type=argparse.FileType('r'))
  parser.add_argument('-o', '--outfile', help="Output file", default=sys.stdout, type=argparse.FileType('w'))

  args = parser.parse_args(arguments)
  args.outfile.write(pypandoc.convert(args.infile, 'rst'))
  args.outfile.close()

if __name__ == '__main__':
  sys.exit(main(sys.argv[1:]))
