#!/bin/bash
OIFS="$IFS"
IFS=$'\n'
echo "working"
# for filename in `find $(pwd) -type f -name "*.pdf"`; do
for filename in *.pdf; do
  echo -n "."
  filename=$(basename "$filename");
  # [[ "$filename" = "${filename%[[:space:]]*}" ]] && continue;
  file_type=$(file --mime "$filename" | cut -d ':' -f2 | cut -d ' ' -f2);
  [[ $file_type == "application/pdf;" ]] || (echo "not pdf" $(file --mime "$filename"); continue);
  nname=$(pdfinfo "$filename" | grep 'Title' | cut -d ':' -f2 | tr -d '\n')
  [[ $nname ]] || nname="$filename";
  nname=$(echo -n $nname | sed -e 's/^[ \t]*//' | sed 's/ /-/g' |  sed 's/[^a-z  A-Z 0-9 \.]/-/g' | tr -s '\0-\255')
  [[ $nname == "" ]] && nname=$(echo -n "$filename" | sed -e 's/^[ \t]*//' | sed 's/ /-/g' |  sed 's/[^a-z  A-Z 0-9 \.]/-/g' | tr -s '\0-\255')
  [[ $nname == *"pdf"* ]] || nname=$nname.pdf
  # nname=$(echo "$filename" | sed 's/ /-/g' | tr -dc '[:alnum:]-_.' | tr -s '-')
  [[ "$filename" == $nname ]] && continue
  echo "Renaming $filename as $nname"
  [[ $nname != "" ]] && mv "$filename" $nname
done
IFS="$OIFS"

# nname=$(pdfinfo N5625_5.pdf | grep 'Title' | cut -d ':' -f2 | tr -d '\n')
# OIFS="$IFS"
# IFS=$'\n'
# for filename in `find . -type f -name "*.*"`; do
#   filename=$(basename "$filename")
#   # file_type=$(file --mime "$filename" | cut -d ':' -f2 | cut -d ' ' -f2)
#   # [[ $file_type == "application/pdf;" ]] || echo "not pdf" $(file --mime "$filename")
#   # nname=$(pdfinfo "$filename" | grep 'Title' | cut -d ':' -f2 |  sed -e 's/^[ \t]*//' | sed 's/ /-/g')
#   nname=$(echo "$filename" | sed 's/ /-/g' | tr -dc '[:alnum:]-_.' | tr -s '-')
#   [[ $nname != "" ]] && mv "$filename" $nname
# done
# IFS="$OIFS"
