#!/usr/bin/env python
# Get the full absolute path (realpath) of args
# @author Weston Ruter (@westonruter) http://weston.ruter.net/

import sys
from pathlib import Path

for path in sys.argv[1:]:
    print(Path(path).absolute())
